
services:
  # postgres_mcp_server:
  #   image: postgres:15
  #   container_name: postgres_mcp_server
  
  redis_storage:
    image: redis:7-alpine
    expose:
      - "6379"
  
  framework_handler:
    build: ./framework_handler
    container_name: framework_handler
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - FRAMEWORK_LIST=langchain,langchain
      - USER_QUERY="How much wood would a woodchuck chuck if a woodchuck could chuck wood?"
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

